name: Build Workflow

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    name: Build Docker 
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/user-service:${{ github.sha }} .
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/user-service:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    name: Deploy via argoCD
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "zeabix-cloud-native/pttgc-devops-lab10-cd"
      - name: Update image version
        run: yq -i e ".userService.tag=${{ github.sha }}" values.yaml
        working-directory: ./production
