name: Test ACR

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  login:
    runs-on: ubuntu-latest
    name: Login ACR
    steps:
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}