name: Test ACR

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy via argoCD
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "zeabix-cloud-native/pttgc-devops-lab10-cd"
          persist-credentials: false
          fetch-depth: 0
      - name: Update image version
        run: yq -i e '.userService.tag="${{ github.sha }}"' values.yaml
        working-directory: ./production
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: "zeabix-cloud-native/pttgc-devops-lab10-cd"